import { environment } from './../../../environments/environment';
import { PostsPage } from './../model/PostsPage';
import { PostDTO } from './../model/PostDTO';
/**
 * SpongeblogSP API
 * Spongeblog blogging API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Inject, Injectable, Optional, } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import * as models from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class PagesApi {

  protected basePath = environment.apiUrl;
  public defaultHeaders: Headers = new Headers();
  public configuration: Configuration = new Configuration();

  constructor(protected http: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string,
  @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
    }
  }

  /**
   * All pages.
   * Returns all pages having no category assigned.
   * @param withoutCategory Filter pages without a category.
   */
  public apiV1PagesGetUsingGET(withoutCategory?: boolean, extraHttpRequestParams?: any): Observable<PostsPage> {
    const path = this.basePath + '/api/v1/pages';

    let queryParameters = new HttpParams();
    if (withoutCategory !== undefined) {
      queryParameters = queryParameters.set('without-category', <any>withoutCategory);
    }
    return this.http.get(path, {params: queryParameters});
  }

  /**
   * Get Page
   * Fetches Page with defined Id.
   * @param pageId Unique identifier of a Page;
   */
  public apiV1PostsPageIdGetUsingGET(pageId: number, extraHttpRequestParams?: any): Observable<PostDTO> {
    const path = this.basePath + '/api/v1/pages/${pageId}'
      .replace('${' + 'pageId' + '}', String(pageId));
    // verify required parameter 'pageId' is not null or undefined
    if (pageId === null || pageId === undefined) {
      throw new Error('Required parameter pageId was null or undefined when calling apiV1PostsPageIdGetUsingGET.');
    }
    return this.http.get<PostDTO>(path);
  }
}
